spring.application.name=B3Pokemon
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=LewisB3pourlebachelor205
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=PokemonLeagueDB;encrypt=false

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true